import React, { useState, useEffect } from 'react';
import { Routes, Route, Navigate, useNavigate, useLocation } from 'react-router-dom';
import './styles.css';
import config from './config.json'; // Auto-generated by deploy.js

// Import Components
import Login from './components/Login';
import AdminDashboard from './components/AdminDashboard';
import IssuerDashboard from './components/IssuerDashboard';
import UserDashboard from './components/UserDashboard';
import Profile from './components/Profile';
import SuperAdminDashboard from './components/SuperAdminDashboard';

function App() {
  const navigate = useNavigate();
  const location = useLocation();
  const [token, setToken] = useState(null);
  const [role, setRole] = useState(null);
  
  // Login States
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [hardhatKey, setHardhatKey] = useState('');
  const [isFirstLogin, setIsFirstLogin] = useState(false);
  
  // Admin States
  const [newEmail, setNewEmail] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [newRole, setNewRole] = useState('issuer');
  const [usersList, setUsersList] = useState([]);
  
  // Issuer States
  const [credentialText, setCredentialText] = useState('');
  const [contractAddress, setContractAddress] = useState(config.contractAddress || '');
  const [file, setFile] = useState(null);
  const [revokeCredentialId, setRevokeCredentialId] = useState('');
  const [issuedDocuments, setIssuedDocuments] = useState([]);
  
  // Verify States
  const [verifyCredentialText, setVerifyCredentialText] = useState('');
  const [verifyContractAddress, setVerifyContractAddress] = useState(config.contractAddress || '');
  const [verifyFile, setVerifyFile] = useState(null);
  const [verifyResult, setVerifyResult] = useState('');

  // Verifier / Normal User States
  const [myDocuments, setMyDocuments] = useState([]);

  // Handle Initial Redirect
  useEffect(() => {
    if (!token && location.pathname !== '/login') {
      navigate('/login');
    }
  }, [token, location.pathname, navigate]);
  
  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const endpoint = isFirstLogin ? '/api/auth/first_login' : '/api/auth/login';
      const payload = { email, password };
      if (isFirstLogin) payload.hardhat_key = hardhatKey;
      
      const res = await fetch(`http://localhost:3000${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      
      if (data.error) {
        alert(data.error);
        return;
      }
      
      setToken(data.token);
      setRole(data.role);
      
      if (isFirstLogin && data.role === 'issuer') {
         localStorage.setItem('hardhatKey', hardhatKey);
      }
      
      if (data.role === 'super_admin') {
          navigate('/super-admin');
      }
      else if (data.role === 'master_admin') {
          navigate('/admin');
          fetchUsers(data.token);
      }
      else if (data.role === 'issuer') {
          navigate('/issuer');
          fetchIssuedDocuments(data.token);
      }
      else {
          navigate('/verifier');
          fetchMyDocuments(data.token);
      }
      
    } catch (err) {
      alert("Error logging in");
    }
  };

  const handleLogout = () => {
    setToken(null);
    setRole(null);
    navigate('/login');
    // Clear sensitive states
    setEmail('');
    setPassword('');
    setHardhatKey('');
  };

  const fetchUsers = async (adminToken) => {
      try {
          const res = await fetch(`http://localhost:3000/api/users?masterAdminToken=${adminToken}`);
          const data = await res.json();
          if (data.users) setUsersList(data.users);
      } catch (err) {
          console.error("Failed to fetch users", err);
      }
  };

  const handleDeleteUser = async (userId) => {
      if (!window.confirm('Are you sure you want to delete this user?')) return;
      try {
          const res = await fetch(`http://localhost:3000/api/users/${userId}`, {
              method: 'DELETE',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ masterAdminToken: token })
          });
          const data = await res.json();
          if (data.error) alert(data.error);
          else {
              alert(data.message);
              fetchUsers(token);
          }
      } catch (err) {
          alert('Error deleting user');
      }
  };

  const handleChangePassword = async (userId) => {
      const newPwd = window.prompt('Enter new password for this user (at least 6 characters):');
      if (!newPwd) return;
      try {
          const res = await fetch(`http://localhost:3000/api/users/${userId}/password`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ masterAdminToken: token, newPassword: newPwd })
          });
          const data = await res.json();
          if (data.error) alert(data.error);
          else alert(data.message);
      } catch(err) {
          alert('Error updating password');
      }
  };

  const handleCreateUser = async (e) => {
    e.preventDefault();
    try {
      const res = await fetch('http://localhost:3000/api/auth/create_user', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          masterAdminToken: token,
          email: newEmail,
          password: newPassword,
          role: newRole
        })
      });
      const data = await res.json();
      if (data.error) {
          alert(data.error);
      } else {
          if (data.credentials) {
              alert(`USER CREATED!\n\nEmail: ${data.credentials.email}\nPassword: ${data.credentials.password}\nHardhat Key: ${data.credentials.hardhat_key}\n\nPlease copy these securely.`);
              fetchUsers(token);
          } else {
              alert(data.message);
          }
      }
    } catch (err) {
      alert("Error creating user");
    }
  };

  const handleIssue = async (e) => {
    e.preventDefault();
    if (!file) return alert("Select a PDF to issue");
    try {
      const formData = new FormData();
      formData.append('credentialText', credentialText);
      formData.append('contractAddress', contractAddress);
      formData.append('issuerToken', token);
      formData.append('document', file);
      formData.append('hardhatKey', localStorage.getItem('hardhatKey') || hardhatKey);

      const res = await fetch('http://localhost:3000/api/issue', {
        method: 'POST',
        body: formData
      });
      const data = await res.json();
      if (data.error) alert(data.error);
      else {
          alert(`Issued! TX Hash: ${data.transactionHash}`);
          fetchIssuedDocuments(token);
      }
    } catch (err) {
      alert("Error issuing document");
    }
  };

  const handleRevoke = async (e, directCredentialId = null) => {
    if (e) e.preventDefault();
    const idToRevoke = directCredentialId || revokeCredentialId;
    if (!idToRevoke) return alert("Enter a credential ID to revoke");
    if (!window.confirm("Are you sure you want to permanently revoke this document?")) return;
    try {
      const res = await fetch('http://localhost:3000/api/revoke', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          credentialId: idToRevoke,
          contractAddress: contractAddress,
          issuerToken: token,
          hardhatKey: localStorage.getItem('hardhatKey') || hardhatKey
        })
      });
      const data = await res.json();
      if (data.error) alert(data.error);
      else {
          alert(`Document revoked successfully! TX Hash: ${data.transactionHash}`);
          setRevokeCredentialId('');
          fetchIssuedDocuments(token);
      }
    } catch (err) {
      alert("Error revoking document");
    }
  };

  const handleVerify = async (e) => {
    e.preventDefault();
    if (!verifyFile) return alert("Select a PDF to verify");
    try {
      setVerifyResult("Verifying...");
      const formData = new FormData();
      formData.append('credentialText', verifyCredentialText);
      formData.append('contractAddress', verifyContractAddress);
      formData.append('document', verifyFile);

      const res = await fetch('http://localhost:3000/api/verify', {
        method: 'POST',
        body: formData
      });
      const data = await res.json();
      if (data.error) {
         setVerifyResult("Error: " + data.error);
      } else {
         if (data.verified) {
             setVerifyResult(`✅ VERIFIED! Authentic document issued by ${data.issuer} on ${data.issuedAt}`);
         } else {
             setVerifyResult(`❌ FAILED: ${data.message}`);
         }
      }
    } catch (err) {
      setVerifyResult("Error verifying document");
    }
  };

  const fetchMyDocuments = async (userToken) => {
      try {
          const res = await fetch(`http://localhost:3000/api/my-documents?token=${userToken}`);
          const data = await res.json();
          if (data.documents) setMyDocuments(data.documents);
      } catch (err) {
          console.error("Failed to fetch documents", err);
      }
  };

  const fetchIssuedDocuments = async (userToken) => {
      try {
          const res = await fetch(`http://localhost:3000/api/issued-documents?token=${userToken}`);
          const data = await res.json();
          if (data.documents) setIssuedDocuments(data.documents);
      } catch (err) {
          console.error("Failed to fetch issued documents", err);
      }
  };

  return (
    <div className="app-root">
      <Routes>
        <Route path="/" element={<Navigate to={token ? `/${role === 'super_admin' ? 'super-admin' : role === 'master_admin' ? 'admin' : role === 'issuer' ? 'issuer' : 'verifier'}` : "/login"} />} />
        
        <Route path="/login" element={
          <Login 
            email={email} setEmail={setEmail}
            password={password} setPassword={setPassword}
            isFirstLogin={isFirstLogin} setIsFirstLogin={setIsFirstLogin}
            hardhatKey={hardhatKey} setHardhatKey={setHardhatKey}
            handleLogin={handleLogin}
          />
        } />

        <Route path="/super-admin" element={
          role === 'super_admin' ? (
            <SuperAdminDashboard token={token} handleLogout={handleLogout} />
          ) : <Navigate to="/login" />
        } />

        <Route path="/admin" element={
          role === 'master_admin' ? (
            <AdminDashboard 
              newEmail={newEmail} setNewEmail={setNewEmail}
              newPassword={newPassword} setNewPassword={setNewPassword}
              newRole={newRole} setNewRole={setNewRole}
              usersList={usersList}
              handleCreateUser={handleCreateUser}
              handleChangePassword={handleChangePassword}
              handleDeleteUser={handleDeleteUser}
              handleLogout={handleLogout}
              token={token}
            />
          ) : <Navigate to="/login" />
        } />

        <Route path="/issuer" element={
          role === 'issuer' ? (
            <IssuerDashboard 
              contractAddress={contractAddress} setContractAddress={setContractAddress}
              credentialText={credentialText} setCredentialText={setCredentialText}
              file={file} setFile={setFile}
              revokeCredentialId={revokeCredentialId} setRevokeCredentialId={setRevokeCredentialId}
              issuedDocuments={issuedDocuments}
              handleIssue={handleIssue}
              handleRevoke={handleRevoke}
              verifyContractAddress={verifyContractAddress} setVerifyContractAddress={setVerifyContractAddress}
              verifyCredentialText={verifyCredentialText} setVerifyCredentialText={setVerifyCredentialText}
              verifyFile={verifyFile} setVerifyFile={setVerifyFile}
              handleVerify={handleVerify}
              verifyResult={verifyResult}
              handleLogout={handleLogout}
            />
          ) : <Navigate to="/login" />
        } />

        <Route path="/verifier" element={
          role === 'normal_user' ? (
            <UserDashboard 
              myDocuments={myDocuments}
              verifyContractAddress={verifyContractAddress} setVerifyContractAddress={setVerifyContractAddress}
              verifyCredentialText={verifyCredentialText} setVerifyCredentialText={setVerifyCredentialText}
              verifyFile={verifyFile} setVerifyFile={setVerifyFile}
              handleVerify={handleVerify}
              verifyResult={verifyResult}
              handleLogout={handleLogout}
            />
          ) : <Navigate to="/login" />
        } />

        <Route path="/profile" element={
          token ? (
            <Profile 
              email={email} 
              role={role} 
              issuedDocuments={issuedDocuments} 
              myDocuments={myDocuments} 
              handleLogout={handleLogout} 
              handleRevoke={handleRevoke}
            />
          ) : <Navigate to="/login" />
        } />

        {/* Catch-all route */}
        <Route path="*" element={<Navigate to="/" />} />
      </Routes>
    </div>
  );
}

export default App;
